# Generated by Django 4.2.11 on 2024-04-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('anons', models.CharField(max_length=150, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('datetime_pub', models.DateTimeField(verbose_name='Дата Мероприятия')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('image', models.ImageField(blank=True, upload_to='activities/', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='ParticipationActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, verbose_name='Емайл')),
                ('education_entity', models.CharField(blank=True, max_length=150, null=True, verbose_name='Образовательное учреждение')),
                ('status', models.CharField(choices=[('UNK', 'На рассмотрении'), ('ACC', 'Принята'), ('UNA', 'Отклонена')], default='UNK', max_length=3)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_activities', to='activities.activities', verbose_name='Мероприятие')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_activities', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участие в мероприятии',
                'verbose_name_plural': 'Участие в мероприятиях',
            },
        ),
        migrations.AddConstraint(
            model_name='participationactivities',
            constraint=models.UniqueConstraint(fields=('activity', 'created_by'), name='unique_participation'),
        ),
    ]
